### ISSUE TITLE
Version 2 Checklist

### ISSUE THREAD

**Issue by drewjbartlett** [rapidjs/rapid.js#50]
##### Documentation

- [ ] Rewrite version 2 docs to reflect updates
- [ ] Rewrite version 2 docs in nuxt (and maybe markdown)
- [ ] Add guide for writing tests

##### Fixes

- [x] allow data with DELETE
- [x] Fix polluted params issue when where params send twice

##### Enhancements

- [x] `api` renamed to `http`
- [x] rename `apiConfig` to `httpConfig`
- [x] swap `qs` for `qs-stringify` since we only use that method https://www.npmjs.com/package/qs-stringify
- [x] Allow for other promise-based http services to be used in place of axios with injection
- [x] Fix nasty inheritance chain
- [x] Add `.default` helper to go with `model` / `collection`
- [x] Remove spread from request methods (it's not really useful)
- [ ] Allow data to be passed into request like `photo.get('/tags', { order: orders.ASC })`
- [ ] Add TypeScript Support while maintaining `.js` files
- [ ] Properly declare and import type definitions #41 
- [ ] Rewrite Auth to be a mixin and extract to package -- rewrite tests for it
- [ ] Use `deepmerge` instead of lodash
- [x] Rename `withData` to `withConfig`
- [x] Remove Custom Routes
- [x] Remove interceptors
- [x] Remove `qs-stringify` with old debugger
- [x] Remove `axios` entirely
- [x] Remove `httpConfig` from config
- [x] Remove `debug` from config
- [ ] Add mixins array to allow for creating new methods (auth / base)

##### Build
- [ ] Add build tool to minify or gzip files on dist
- [x] Remove `prepublish` hook and replace with: Use `prepare` for build steps and `prepublishOnly` for upload-only.

##### Tests

- [x] Extract debugger to allow easier testing
- [x] Write new debugging library (mockid)
- [x] Rewrite tests for CRUD
- [x] Rewrite tests for custom-route
- [x] Rewrite tests for extensions
- [x] Rewrite tests for id
- [x] Rewrite tests for request
- [x] Rewrite tests for request-hooks
- [x] Rewrite tests for routes
- [ ] Rewrite tests for with
- [x] Write tests for `model`, `collection`, `default`

I can add a contributing guide for this. But for now:

1. Please run `npm run unit:watch` while working on new features and fixes. Do you best to make _small_ changes while always keeping the tests green.
2. Only submit _small_ pull requests that are specific to the task. (Horizontal refactoring). If you see something else unrelated that needs fixing, make a ticket or write down a note to address it later

For now we can use issues or projects. @mgred I have not used projects for this but we can look into it!

**Comment by drewjbartlett** [comment]
@mgred let's use this as a base right now. We can work off `develop`and make _small_ pull requests against it while we are working. How would be best for me to delegate detailed tasks to you?

**Comment by ctsstc** [comment]
It might be good to use some of the github templating if you would like people to follow contributing guidelines.

https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by mgred** [comment]
@drewjbartlett cool plan.
> Only submit _small_ pull requests that are specific to the task

I like that workflow, think its quite efficient to do small but qualitative steps

> How would be best for me to delegate detailed tasks to you?

You can give me any task, with a short description in an issue, I think that's enough
BTW, does this list has any priority order?

**Comment by drewjbartlett** [comment]
@ctsstc @mgred I am down to use issues with templates. Also, there is no priority order on that list at the moment. I have taken on a handful of those tasks at the moment. I will break them up and delegate to you guys if you're down
